#runtime: python
#env: flex
#entrypoint: gunicorn -b :$PORT main:app
#
#runtime_config:
#  python_version: 3

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
